### ISSUE TITLE
CSSNext + StyleLint (PostCSS)

### ISSUE THREAD

**Issue by jrodl3r** [choonkending/react-webpack-node#296]
_Proposal:_

Swap **_'postcss-mixins'_**, **_'postcss-nested'_**, **_'postcss-simple-vars'_** and **_'autoprefixer'_** for:
- **_'post-cssnext'_** » [CSSNext](http://cssnext.io/postcss)
- **_'styleLintPlugin'_** » [StyleLint](http://stylelint.io/) ([stylelint-webpack-plugin](https://www.npmjs.com/package/stylelint-webpack-plugin))

---

Liking this setup so far, it provides a lot of really nice features out-of-the-box.

There are a few minor quirks that force you to be more explicit... 

- _nested styles must begin with **"& "** or **"@nest "**_
```css
.foo {
  .bar { }   // doesn't work
  & .bar { } // must have "& " in front of nested declaration
  @nest span & .baz { } // must have "@nest " in front of complex nesting declarations
}
```
- _global style needs to begin with **":global "**_
```css
:global {
  .foo { } // doesn't work
  .baz { }
}
:global .foo { ... } // works
:global .baz { ... }
```
- _global variables, media queries + common files with **@import**, **@apply** and **var(--varName)**_
```css
/* main.css */
@import 'settings';
@import 'common/colors';
@import 'common/buttons';

.button {
  @apply --clearButton;
  font-size: var(--fontSize);
  color: var(--colorRed); /* overrides --colorBlue */
  @media (--medium-screen) {
    background: --colorBlue;
  }
}
```
```css
/* settings.css */
:root {
  --fontSize: 12px;
}

@custom-media --medium-screen (300px < width < 500px);
```
```css
/* common/colors.css */
:root {
  --colorRed: red;
  --colorBlue: blue;
}
```
```css
/* common/buttons.css */
@import 'colors';

:root {
  --button {
    size: 40px 120px;
    color: var(--colorBlue); /* var() is like echo */
  }

  --clearButton {
    @apply --button; /* @apply is like composes */
    background-color: rgba(0,0,0, .5);
  }
}
```

- fits the current webpack / postCSS build system well and StyleLint is quite useful...

<img width="431" alt="screen shot 2016-06-29 at 6 31 40 pm" src="https://cloud.githubusercontent.com/assets/869411/16474036/01aeb66e-3e28-11e6-819c-c75dd9ec3307.png">

<img width="471" alt="screen shot 2016-06-30 at 6" src="https://cloud.githubusercontent.com/assets/869411/16509643/dedadbaa-3ef3-11e6-9e01-69df15439a69.png">

--- 

_**Issues:**_

- Rebuild not triggered when saving `:root { ... }` styles or _partials_ _(ex: settings.css, colors.css, buttons.css)_. Current workaround is to _Tab-back_ to one of the root CSS files (that are being included by the module or container you have loaded in the browser) and _CMD-S_ to trigger webpack / rebuild, StyleLint, etc. [https://github.com/postcss/postcss-loader/issues/58]
